# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fafdb9e640322415416d327a32294cd2aa82a6cf9d7b77626ba29cbe648fffc222033f864e377036e7aadb8aed9be4e1ccc0e9915a4760d092459a63eea0388

test:
  secret_key_base: b4745cdcc7e81b3e02609927a5566b911efe7396c0c118e81e4d5c7cb4f10af66c76b73f55ed08b738bb248e37434e3e2b11c7a66e2f066cd49e39ed9245e50e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
